build:
  image: default-jammy
  environment:
    php:
      version: 8.4.12
      ini:
        'xdebug.mode': 'coverage'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    tests:
      dependencies:
        before:
          - pecl install xdebug
      tests:
        override:
          - command: 'php -d zend_extension=xdebug.so -d xdebug.mode=coverage vendor/bin/pest --coverage --coverage-clover=coverage.xml'
            coverage:
              file: 'coverage.xml'
              format: 'php-clover'
filter:
  excluded_paths:
    - tests/*
    - vendor/*

checks:
  php: true


coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
