filter:
    excluded_paths:
        - 'tests/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

build:
    environment:
        php:
            version: 8.3
    nodes:
        pest:
            environment:
                php: 8.3
            tests:
                override:
                  - command: 'vendor/bin/pest --coverage --coverage-clover=coverage.xml'
                    coverage:
                        file: 'coverage.xml'
                        format: 'php-clover'