filter:
    excluded_paths:
        - 'spec/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

build:
    image: default-bionic
    environment:
        php:
            version: 8.1
            ini:
                'xdebug.mode': 'coverage'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - command: 'bin/phpspec run'
                        coverage:
                            file: 'coverage.xml'
                            format: 'php-clover'
