filter:
    excluded_paths:
        - 'tests/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

build:
    image: default-jammy
    environment:
        php:
            ini:
                'xdebug.mode': 'coverage'
    nodes:
        analysis:
            environment:
                php: 8.3
            tests:
                override:
                    - php-scrutinizer-run
        pest:
            environment:
                php: 8.3
            tests:
                override:
                  - command: 'vendor/bin/pest --coverage --coverage-clover=coverage.xml'
                    coverage:
                        file: 'coverage.xml'
                        format: 'php-clover'