build:
    environment:
        php:
            version: 8.0
    tests:
        override:
            -
                command: 'bin/phpspec run'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
