checks:
    php:
        code_rating: true
        duplication: true

build:
    image: default-bionic
    environment:
        php:
            version: 8.1
            ini:
                'xdebug.mode': 'coverage'
    tests:
        override:
            -
                command: 'bin/phpspec run'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
